[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
cache_path = 'contracts/cache'
broadcast = 'contracts/broadcast'
libs = ['contracts/lib']

remappings = [
  "@chainlink/contracts/=contracts/lib/chainlink-brownie-contracts/contracts",
  "@solmate/=contracts/lib/solmate/src",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
